// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6t0aJNLVa2DGSfPmB4zRObCKiCf2SwIM',
    appId: '1:800355033239:android:bb7df4b8fd923021dac9d2',
    messagingSenderId: '800355033239',
    projectId: 'africa-cdc-2c237',
    databaseURL: 'https://africa-cdc-2c237-default-rtdb.firebaseio.com',
    storageBucket: 'africa-cdc-2c237.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlbBsV6qzRhQ3WY2IMqTR0MeU6o1SpMd8',
    appId: '1:800355033239:ios:ab4d84a3c54bb91edac9d2',
    messagingSenderId: '800355033239',
    projectId: 'africa-cdc-2c237',
    databaseURL: 'https://africa-cdc-2c237-default-rtdb.firebaseio.com',
    storageBucket: 'africa-cdc-2c237.appspot.com',
    iosBundleId: 'com.moh.safemama',
  );
}
